baseURL = "https://blog.ycyun.xyz/"
languageCode = "ko-KR"
title = "블로그"
theme = "hugo-hello-programmer-theme"
DefaultContentLanguage = "kr"
disqusShortname = "ycyun"
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 7
publishDir="docs"

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true

  [[related.indices]]
    name = "keywords"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10

[outputs]
home = ["HTML", "RSS"]


[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"


[author]
  name = "윤여천 (YeoCheon, Yun)"
  email = "ycyun@ycyun.xyz"
  homepage = "https://www.ycyun.xyz"

[params]
    description = "블로그"
